output-formats:
  - format: colored-line-number

run:
  timeout: 3m
  allow-parallel-runners: true
  allow-serial-runners: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - unconvert
    - misspell
    - bodyclose
    - noctx
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - staticcheck
      text: "SA1029"

linters-settings:
  goimports:
    local-prefixes: github.com/MAPiryazev/Wildberries_L1/tree/main/L3/L3.7
  gofmt:
    simplify: true
  misspell:
    locale: US
